# Generated by Django 5.1.6 on 2025-02-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'city'), name='location unique')],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='bookshop.location', verbose_name='Местоположение')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('author', models.ManyToManyField(related_name='books', to='bookshop.author', verbose_name='Автор(ы)')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'release_date'), name='book unique')],
            },
        ),
    ]
