# Generated by Django 5.1.6 on 2025-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, verbose_name='Язык')),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'city'], name='bookshop_lo_country_0bbdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['language'], name='bookshop_la_languag_f72845_idx'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(null=True, related_name='books', to='bookshop.language'),
        ),
    ]
