# Generated by Django 5.1.6 on 2025-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_language_location_bookshop_lo_country_0bbdcf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='language',
            name='bookshop_la_languag_f72845_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='bookshop_lo_country_0bbdcf_idx',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(related_name='books', to='bookshop.language'),
        ),
    ]
