# Generated by Django 5.1.6 on 2025-03-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_remove_language_bookshop_la_languag_f72845_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'surname']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['country', 'city']},
        ),
    ]
