# Generated by Django 5.1.6 on 2025-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['language'], name='bookshop_la_languag_f72845_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'city'], name='bookshop_lo_country_0bbdcf_idx'),
        ),
    ]
